<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IO\Foundation.IO.csproj" />
    <ProjectReference Include="..\Log\Foundation.Log.csproj" />
    <ProjectReference Include="..\Threading\Foundation.Threading.csproj" />
  </ItemGroup>

</Project>
