<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>sql_racer_gamedatabase_sql_1526.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="sql_racer_gamedatabase_sql_1526.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
    <PackageReference Include="Microsoft.SqlServer.SqlManagementObjects" Version="181.12.0" />
    <PackageReference Include="Microsoft.SqlServer.Types" Version="170.1000.7" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.100" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Foundation\Configuration\Foundation.Configuration.csproj" />
    <ProjectReference Include="..\..\Foundation\Data\Foundation.Data.csproj" />
    <ProjectReference Include="..\..\Foundation\DefaultLog\Foundation.DefaultLog.csproj" />
    <ProjectReference Include="..\..\Foundation\Log\Foundation.Log.csproj" />
    <ProjectReference Include="..\DataCommander.Application\DataCommander.Application.csproj" />
  </ItemGroup>

</Project>