<Project>
    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <LangVersion>14.0</LangVersion>
        <Nullable>enable</Nullable>
        <Company>Data Commander</Company>
        <Product>Data Commander</Product>
        <Description>Data Commander</Description>
        <AssemblyVersion>11.0</AssemblyVersion>        
        <RepositoryUrl>https://github.com/csbernath/DataCommander</RepositoryUrl>
        <Features>runtime-async=on</Features>        
    </PropertyGroup>
</Project>