<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.4" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Assertions\Foundation.Assertions.csproj" />
      <ProjectReference Include="..\Diagnostics\Foundation.Diagnostics.csproj" />
    </ItemGroup>

</Project>
