<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0-windows7.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <NoWarn>$(NoWarn);WFO1000</NoWarn>
    <ApplicationIcon>sql_racer_gamedatabase_sql_1526.ico</ApplicationIcon>    
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <WarningsAsErrors>;NU1605;SYSLIB0011;CS8602</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="sql_racer_gamedatabase_sql_1526.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ADODB" Version="7.10.3077" />
    <PackageReference Include="EPPlus" Version="8.6.0" />
    <PackageReference Include="HtmlTextWriter" Version="3.0.2" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.8" />
    <PackageReference Include="Microsoft.Office.Interop.Word" Version="15.0.4797.1004" />
    <PackageReference Include="Microsoft.SqlServer.Compact" Version="4.0.8876.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />   

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Foundation\Assertions\Foundation.Assertions.csproj" />
    <ProjectReference Include="..\..\Foundation\Data.SqlClient\Foundation.Data.SqlClient.csproj" />
    <ProjectReference Include="..\..\Foundation\Data\Foundation.Data.csproj" />
    <ProjectReference Include="..\..\Foundation\Diagnostics\Foundation.Diagnostics.csproj" />
    <ProjectReference Include="..\..\Foundation\Log\Foundation.Log.csproj" />
    <ProjectReference Include="..\..\Foundation\Threading\Foundation.Threading.csproj" />
    <ProjectReference Include="..\..\Foundation\Windows.Forms\Foundation.Windows.Forms.csproj" />
    <ProjectReference Include="..\DataCommander.Api\DataCommander.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="CancelableOperationForm.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>
