using System.Collections.Concurrent;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Diagnostics;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;
using DataCommander.Api;
using DataCommander.Api.Connection;
using DataCommander.Application.ResultWriter;
using Foundation.Log;
using Foundation.Threading;
using Timer = System.Windows.Forms.Timer;

namespace DataCommander.Application.Query;

public sealed partial class QueryForm
{
    private static readonly ILog Log = LogFactory.Instance.GetCurrentTypeLog();
    private readonly MainForm _mainForm;
    private MenuStrip _mainMenu;
    private ToolStripMenuItem _menuItem1;
    private StatusStrip _statusBar;
    private ToolStripMenuItem _mnuDescribeParameters;
    private ToolStripMenuItem _mnuCloseTabPage;
    private ToolStripMenuItem _mnuCancel;
    private ToolStripStatusLabel _sbPanelText;
    private ToolStripStatusLabel _sbPanelTimer;
    private ToolStripStatusLabel _sbPanelRows;
    private ToolStripMenuItem _menuItem2;
    private ToolStripMenuItem _mnuDataGrid;
    private ToolStripMenuItem _mnuHtml;
    private ToolStripMenuItem _mnuRtf;
    private ToolStripMenuItem _menuItem7;
    private ToolStripMenuItem _mnuCommandTypeText;
    private ToolStripMenuItem _mnuCommandTypeStoredProcedure;
    private ToolStripMenuItem _mnuText;
    private TreeView _tvObjectExplorer;
    private Splitter _splitterObjectExplorer;
    private ToolStripMenuItem _menuItem3;
    private Splitter _splitterQuery;
    private TabControl _tabControl;
    private ToolStripMenuItem _menuItem8;
    private ToolStripMenuItem _mnuPaste;
    private ToolStripStatusLabel _sbPanelCaretPosition;
    private ToolStripMenuItem _mnuFind;
    private ToolStripMenuItem _mnuFindNext;
    private ToolStripMenuItem _mnuObjectExplorer;
    private ToolStripMenuItem _menuItem9;
    private ToolStripMenuItem _mnuSaveAs;
    private ToolStripMenuItem _mnuExcel;
    private ToolStripMenuItem _mnuCodeCompletion;
    private ToolStripMenuItem _mnuListMembers;
    private ToolStripMenuItem _mnuGotoQueryEditor;
    private ToolStripMenuItem _mnuCloseAllTabPages;
    private ToolStripMenuItem _mnuGotoMessageTabPage;
    private ToolStripMenuItem _mnuClearCache;
    private ToolStripMenuItem _mnuListView;
    private ToolStripMenuItem _mnuExecuteQueryKeyInfo;
    private ToolStripMenuItem _mnuExecuteQuerySchemaOnly;
    private ToolStripMenuItem _mnuExecuteQuerySingleRow;
    private ToolStripMenuItem _mnuShowShemaTable;
    private ToolStripMenuItem _mnuExecuteQueryXml;
    private ToolStripMenuItem _mnuSave;
    private ToolStripMenuItem _mnuCreateInsert;
    private ToolStripMenuItem _menuResultModeFile;
    private ToolStripStatusLabel _sbPanelTableStyle;
    private ToolStripMenuItem _mnuGoTo;
    private ToolStripMenuItem _mnuDuplicateConnection;
    private ToolStripMenuItem _mnuCreateInsertSelect;
    private ToolStripMenuItem _mnuOpenTable;
    private readonly IContainer components = new Container();
    private readonly string _connectionString;
    private readonly string _connectionName;
    private DbTransaction _transaction;
    private SqlParser _sqlStatement;
    private DbCommand _command;
    private CommandType _commandType = CommandType.Text;
    private IAsyncDataAdapter? _dataAdapter;
    private bool _cancel;
    private readonly Timer _timer = new();
    private readonly Stopwatch _stopwatch = new();
    private readonly int _htmlMaxRecords;
    private readonly int _wordMaxRecords;
    private DataSetResultWriter _dataSetResultWriter;
    private bool _showSchemaTable;
    private readonly StatusStrip _parentStatusBar;
    private readonly TextBoxWriter _textBoxWriter;
    private FindTextForm _findTextForm;
    private readonly int _rowBlockSize;
    private readonly StandardOutput _standardOutput;
    private string? _database;
    private string? _fileName;
    private int _commandTimeout;
    private Font _font;
    private ToolStripMenuItem _mnuRefreshObjectExplorer;
    private ToolStripSeparator _toolStripSeparator2;
    private ToolStripSeparator _toolStripSeparator1;
    private ToolStripSeparator _toolStripSeparator3;
    private ToolStripMenuItem _sQLiteDatabaseToolStripMenuItem;
    private ToolStripMenuItem _exportToolStripMenuItem;
    private ToolStripMenuItem _commitTransactionToolStripMenuItem;
    private ToolStripMenuItem _beginTransactionToolStripMenuItem;
    private ToolStripMenuItem _rollbackTransactionToolStripMenuItem;
    private ToolStripMenuItem _createSqlCeDatabaseToolStripMenuItem;
    private ToolStripMenuItem _insertScriptFileToolStripMenuItem;
    private bool _openTableMode;
    private readonly TabPage _messagesTabPage;
    private readonly RichTextBox _messagesTextBox;
    private readonly TabPage _resultSetsTabPage;
    private readonly TabControl _resultSetsTabControl;
    private ToolStrip? _toolStrip;
    private ToolStripSeparator _toolStripSeparator4;
    private ToolStripSplitButton _executeQuerySplitButton;
    private ToolStripMenuItem _executeQueryMenuItem;
    private ToolStripMenuItem _executeQuerySingleRowToolStripMenuItem;
    private ToolStripMenuItem _cToolStripMenuItem;
    private ToolStripButton _cancelQueryButton;
    private ToolStripMenuItem _executeQueryToolStripMenuItem;
    private ToolStripMenuItem _openTableToolStripMenuItem;
    private ToolStripMenuItem _parseToolStripMenuItem;
    private QueryTextBox _queryTextBox;
    private readonly ConcurrentQueue<InfoMessage> _infoMessages = new();
    private int _errorCount;
    private readonly LimitedConcurrencyLevelTaskScheduler _scheduler = new(1);
    private readonly CancellationTokenSource _cancellationTokenSource = new();
    private readonly EventWaitHandle _enqueueEvent = new(false, EventResetMode.AutoReset);
    private ToolStripMenuItem createCCommandQueryToolStripMenuItem;
    private ToolStripMenuItem undoToolStripMenuItem;
    private ToolStripMenuItem redoToolStripMenuItem;
    private readonly ColorTheme? _colorTheme;
}